// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	"database/sql"
)

type Acronym struct {
	ID          int64
	Uuid        string
	ShortForm   string
	LongForm    string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type AcronymCategory struct {
	ID         int64
	AcronymID  int64
	CategoryID int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Category struct {
	ID          int64
	Uuid        string
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Note struct {
	ID        int64
	Uuid      string
	Note      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type NoteJoiner struct {
	ID        int64
	AcronymID sql.NullInt64
	NoteID    int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
